language: php
php: 7.3.2
os: linux
git: 
  lfs_skip_smudge: true

notifications:
  slack:
    secure: IbP8RjYvxRfrIT0Max/EnveA5x58c2mOu2h7ylOfibdryW6Dg5sq0rSehjtgortSTN+KWm3GX/c+c566XsIbU73/49Sp6rF9Hfi8hfanwoufCeXN3X35gsDRmATA5PvL/QTTYEBr5XPmW9Mq8yAFxvvq9wW2a3tUJ6NwsH52t33Uscr+Cc+4n03O7yfB2pcdZFztYY6rfgEOKcBaa4/+0f7JeuhhO/s9A4ipFNBNipQLx1wbxulLJPnQBNr5nIFX1FXkVfUS+zNjJCpkhmDWqMHu7YDNbO49oOfeKkjk65Qd5sKHr6PP5ejZ73YtySo/cc0JmmV9lguFN6OKh/Gdx9D2QPKL2ZUwSGNc1HzXLEAvlCp24I4yRm/ti8YiVDhzU4aDrrb1gv39RaEJqAY59LgSBubMCMI8ZlSwFX58J8zEo4g8g0r5xqeTl9W+N6vWArYvb02nv5W7KBzkyteV7+1GmEB7WCv2MOzq1mHv077CHefL6QjodFc4xikce/CVfh6Wgn0BC5sOIx+WtV6pcLTAr+03Ibp21iHj6PpdlMQ9xurQs7k5rqgDVjdMcvuCHB0Sb/KF0EMe0HEE2qpOmGCkExDji9yScgqgJz071Uh5V5LHJVK9C74/k6Db1eKc9hOGDaLON7iuH9u7l6T/bUBmg4JX/wuUqXKhEpIpIdY=
  on_success: change
  on_failure: always

tags: true
branches:
  only: 
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+/

services:
  - docker

cache:
  directories:
    # we cache the SDK so we don't have to download it again on subsequent builds
    - $HOME/google-cloud-sdk

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 

before_script:
  # remove xdebug to speed up testing
  - phpenv config-rm xdebug.ini
  - cp .env.example .env
  - docker version
  - docker-compose up --build -d 
  - docker-compose exec app php --version
  - docker-compose exec app composer --version
  - docker-compose exec database mysql --version
  - docker-compose exec app /bin/bash -c scripts/afterclone.sh
  - docker-compose exec -d app php7 artisan serve --host=0.0.0.0 --port=80
script:
  - docker-compose exec app ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php --testdox tests

# TODO: uncomment when cloud is available
# before_deploy:
#   - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
#       rm -rf $HOME/google-cloud-sdk;
#       curl https://sdk.cloud.google.com | bash > /dev/null;
#     fi
#   - source $HOME/google-cloud-sdk/path.bash.inc
#   - gcloud version
#   # TODO: use kube?
#   # - gcloud components update kubectl
#   # - kubectl version
# deploy:
#   skip_cleanup: true
#   provider: script
#   script: bash scripts/deploy.sh "TODO@gmail.com" "/path/to/TODO"
#   on:
#     tags: true