version: '2'

services:

  # The Application
  app:
    image: app-image
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "8000:80"

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "33061:3306"

volumes:
  dbdata: