# for local development and CI
# pass SEED=true or TEST=true for seeds or testing
version: '2'

services:

  # The Application
  app:
    build:
      context: .
      args:
        SEED: ${SEED}
        UNIT_TEST: ${UNIT_TEST}
        E2E_TEST: ${E2E_TEST}
    env_file:
      - .env
    ports:
      - "${PORT}:80"

  # The Database
  database:
    image: mariadb:10.1.38
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "33061:3306"

volumes:
  dbdata:
