version: '2.1'

services:

  # The Application
  app:
    build:
      context: .
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "${PORT}:80"

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "33061:3306"

  e2e:
    build:
      context: e2e/
      args:
        SERVER_URL: http://app:80 

volumes:
  dbdata:
