version: '2'
services:
    app:
      build:
        context: https://${GITHUB_TOKEN}@github.com/DarkGeekMS/ApeX-Server.git#${BRANCH}
      env_file:
        - .env
      ports:
        - "80:80"
      volumes:
        - front:/app/TODO
        - ./.env:/app/.env
volumes:
  front:
